define(function() {
	return {
		name: '品牌',
		name_en: 'Brand',
		role: ['nav'],
		path: 'alimama/brand/story/story',
		href: '#/brand/story',
		children: [{
			name: '品牌故事',
			name_en: 'Brand Story',
			role: [],
			path: 'alimama/brand/story/story',
			href: '#/brand/story'
		}, {
			name: '标志',
			name_en: 'Logo',
			role: [],
			path: 'alimama/brand/logo/logo',
			href: '#/brand/logo'
		}, {
			name: '吉祥物',
			name_en: 'Mascot',
			role: [],
			path: 'alimama/brand/mascot/mascot',
			href: '#/brand/mascot'
		}, {
			name: '字体',
			name_en: 'Typography',
			role: [],
			path: 'alimama/brand/typography/typography',
			href: '#/brand/typography'
		}, {
			name: '色盘',
			name_en: 'Color Palettes',
			role: [],
			path: 'alimama/brand/color_palettes/color_palettes',
			href: '#/brand/color_palettes'
		}, {
			name: '辅助图形',
			name_en: 'Shapes',
			role: [],
			path: 'alimama/brand/shapes/shapes',
			href: '#/brand/shapes'
		}, {
			name: '图标',
			name_en: 'Icon',
			role: [],
			path: 'alimama/brand/icon/icon',
			href: '#/brand/icon'
		}, {
			name: '网格系统',
			name_en: 'Grid_Systems',
			role: [],
			path: 'alimama/brand/grid_systems/grid_systems',
			href: '#/brand/grid_systems'
		}, {
			name: '案例',
			name_en: 'Examples',
			role: [],
			path: 'alimama/brand/examples/examples',
			href: '#/brand/examples'
		}]
	}
})