/* global define */
define(function() {
	return {
		name: '图表',
		name_en: 'Chart',
		role: ['nav'],
		path: 'alimama/chart/index/README.md',
		href: '#/chart/index',
		children: [{
			name: 'Chartx',
			name_en: '',
			role: [],
			path: 'alimama/chart/index/README.md',
			href: '#/chart/index'
		}, {
			name: '所有',
			name_en: 'All',
			role: [],
			path: 'alimama/chart/all/README.md',
			href: '#/chart/all'
		}, {
			name: '折线图',
			name_en: 'Line',
			role: [],
			path: 'alimama/chart/line/README.md',
			href: '#/chart/line'
		}, {
			name: '柱状图',
			name_en: 'Bar',
			role: [],
			path: 'alimama/chart/bar/README.md',
			href: '#/chart/bar'
		}, {
			name: '饼图',
			name_en: 'Pie',
			role: [],
			path: 'alimama/chart/pie/README.md',
			href: '#/chart/pie'
		}, {
			name: '地图',
			name_en: 'Map',
			role: [],
			path: 'alimama/chart/map/README.md',
			href: '#/chart/map'
		}, {
			name: '雷达图',
			name_en: 'Radar',
			role: [],
			path: 'alimama/chart/radar/README.md',
			href: '#/chart/radar'
		}, {
			name: '散点图',
			name_en: 'Scat',
			role: [],
			path: 'alimama/chart/scat/README.md',
			href: '#/chart/scat'
		}, {
			name: '拓扑图',
			name_en: 'Topo',
			role: [],
			path: 'alimama/chart/topo/README.md',
			href: '#/chart/topo'
		}, {
			name: '进度图',
			name_en: 'Progress',
			role: [],
			path: 'alimama/chart/progress/README.md',
			href: '#/chart/progress'
		}, {
			name: '韦恩图',
			name_en: 'Venn',
			role: [],
			path: 'alimama/chart/venn/README.md',
			href: '#/chart/venn'
		}, {
			name: '和铉图',
			name_en: 'Chord',
			role: [],
			path: 'alimama/chart/chord/README.md',
			href: '#/chart/chord'
		}, {
			name: '混合图表',
			name_en: 'Hybrid',
			role: [],
			path: 'alimama/chart/hybrid/README.md',
			href: '#/chart/hybrid'
		}]
	}
})